title: Des zakailleries pour une zako
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5189906780142337
  brandStrength: 0.9201912598218769
  rhythmicContrast: 0.5190431505907327
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  lightness: 0.9987952755764127
typography_spectrum: 0.4741013229358941
description: '-P-'
layout_spectrum: 0.8768972
name: Pooja in Paris
