title: Des zakailleries pour une zako
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8507589
  brandStrength: 0.9201912598218769
  lightness: 0.4848229
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  rhythmicContrast: 0.7175379
typography_spectrum: 0.5438449
description: '-P-'
layout_spectrum: 0.8768972
name: Pooja in Paris
